---
version: 2
jobs:
  deploy:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: curl https://mozilla.cloud.looker.com/webhooks/projects/looker-hub/deploy
workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
            tags:
              only: /.*/
