---
version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - run: curl https://mozilla.cloud.looker.com/webhooks/projects/looker-hub/deploy
workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
            tags:
              only: /.*/
